version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/impact-app/web/staticfiles
      - media_volume:/home/impact-app/web/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/impact-app/web/staticfiles
      - media_volume:/home/impact-app/web/media
    ports:
      - 1550:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume: