# Generated by Django 2.1.7 on 2019-04-18 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('articles', models.IntegerField(default=0)),
                ('articles_as_first_author', models.IntegerField(default=0)),
                ('articles_with_citations', models.IntegerField(default=0)),
                ('books', models.IntegerField(default=0)),
                ('patents', models.IntegerField(default=0)),
                ('datasets', models.IntegerField(default=0)),
                ('tools', models.IntegerField(default=0)),
                ('book_citations', models.IntegerField(default=0)),
                ('dataset_citations', models.IntegerField(default=0)),
                ('patent_citations', models.IntegerField(default=0)),
                ('tools_citations', models.IntegerField(default=0)),
                ('total_citations', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('url', models.URLField(blank=True, null=True)),
                ('language', models.CharField(default='eng', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_author', models.BooleanField(default=False)),
                ('corresponding_author', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wikipage', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float'), ('list', 'List'), ('dict', 'Dictionary')], default='int', max_length=100)),
                ('source', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('web_page', models.URLField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True)),
                ('orcid', models.CharField(blank=True, max_length=50, null=True)),
                ('scopus_id', models.CharField(blank=True, max_length=50, null=True)),
                ('pmc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('scientific_publications_as_first_author', models.IntegerField(default=0)),
                ('scientific_publications_with_citations', models.IntegerField(default=0)),
                ('books', models.IntegerField(default=0)),
                ('patents', models.IntegerField(default=0)),
                ('datasets', models.IntegerField(default=0)),
                ('tools', models.IntegerField(default=0)),
                ('book_citations', models.IntegerField(default=0)),
                ('dataset_citations', models.IntegerField(default=0)),
                ('patent_citations', models.IntegerField(default=0)),
                ('tools_citations', models.IntegerField(default=0)),
                ('total_citations', models.IntegerField(default=0)),
                ('h_index', models.IntegerField(default=0)),
                ('i10_index', models.IntegerField(default=0)),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sci_impact.Artifact')),
                ('doi', models.CharField(blank=True, max_length=255, null=True)),
                ('pages', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_db', models.CharField(choices=[('gscholar', 'Google Scholar'), ('wos', 'Web of Science'), ('scopus', 'Scopus'), ('pubmed', 'PubMed'), ('other', 'Other')], default='other', max_length=100)),
                ('repo_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.CustomField')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Publication')),
            ],
            bases=('sci_impact.artifact',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sci_impact.Artifact')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
            ],
            bases=('sci_impact.artifact',),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sci_impact.Artifact')),
            ],
            bases=('sci_impact.artifact',),
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sci_impact.Artifact')),
            ],
            bases=('sci_impact.artifact',),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('artifact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sci_impact.Artifact')),
                ('source_repo', models.URLField(blank=True, null=True)),
            ],
            bases=('sci_impact.artifact',),
        ),
        migrations.AddField(
            model_name='institution',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Region'),
        ),
        migrations.AddField(
            model_name='institution',
            name='scientists',
            field=models.ManyToManyField(through='sci_impact.Affiliation', to='sci_impact.Scientist'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Country'),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Region'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Artifact'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Scientist'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Institution'),
        ),
        migrations.AddField(
            model_name='artifactcitation',
            name='from_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_artifact', to='sci_impact.Artifact'),
        ),
        migrations.AddField(
            model_name='artifactcitation',
            name='to_artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_artifact', to='sci_impact.Artifact'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Institution'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='scientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Scientist'),
        ),
        migrations.AlterUniqueTogether(
            name='artifactcitation',
            unique_together={('from_artifact', 'to_artifact')},
        ),
    ]
