# Generated by Django 2.1.7 on 2019-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='conference_ranking',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='impact_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
