# Generated by Django 2.1.7 on 2019-04-23 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0002_auto_20190423_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float'), ('list', 'List'), ('dict', 'Dictionary')], default='journal', max_length=100)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('impact_factor', models.IntegerField(blank=True, null=True)),
                ('conference_ranking', models.CharField(blank=True, max_length=10, null=True)),
                ('quartile', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customfield',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='article',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Venue'),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
