# Generated by Django 2.1.7 on 2019-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0003_auto_20190423_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='issn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
