# Generated by Django 2.1.7 on 2019-04-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0004_venue_issn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='keywords',
        ),
    ]
