# Generated by Django 2.1.7 on 2019-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0007_auto_20190425_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
