# Generated by Django 2.1.7 on 2019-04-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0008_auto_20190425_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='scientists',
        ),
    ]
