# Generated by Django 2.1.7 on 2019-04-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0010_auto_20190425_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='issue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
