# Generated by Django 2.1.7 on 2019-04-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0013_auto_20190426_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
