# Generated by Django 2.1.7 on 2019-04-26 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0014_auto_20190426_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientist',
            old_name='scientific_publications_as_first_author',
            new_name='articles',
        ),
        migrations.RenameField(
            model_name='scientist',
            old_name='scientific_publications_with_citations',
            new_name='articles_as_first_author',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='pmc_id',
        ),
        migrations.RemoveField(
            model_name='scientist',
            name='scopus_id',
        ),
        migrations.AddField(
            model_name='scientist',
            name='articles_citations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scientist',
            name='articles_with_citations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scientist',
            name='scientist_ids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.CustomField'),
        ),
    ]
