# Generated by Django 2.1.7 on 2019-04-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0015_auto_20190426_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='alternative_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
