# Generated by Django 2.1.7 on 2019-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0016_country_alternative_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorship',
            name='last_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scientist',
            name='articles_as_last_author',
            field=models.IntegerField(default=0),
        ),
    ]
