# Generated by Django 2.1.7 on 2019-05-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0017_auto_20190430_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.TextField(),
        ),
    ]
