# Generated by Django 2.1.7 on 2019-05-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0018_auto_20190502_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
