# Generated by Django 2.1.7 on 2019-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0019_scientist_is_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='is_pi_inb',
            field=models.BooleanField(default=False),
        ),
    ]
