# Generated by Django 2.1.7 on 2019-05-13 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0020_scientist_is_pi_inb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationNet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_collaborations', models.IntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Article')),
                ('scientist_A', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientist_A', to='sci_impact.Scientist')),
                ('scientist_B', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientist_B', to='sci_impact.Scientist')),
            ],
        ),
    ]
