# Generated by Django 2.1.7 on 2019-05-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0021_collaborationnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationnet',
            name='article',
        ),
    ]
