# Generated by Django 2.1.7 on 2019-05-14 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0022_remove_collaborationnet_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today)),
                ('num_nodes', models.IntegerField(default=0)),
                ('num_edges', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='collaborationnet',
            name='id',
        ),
        migrations.AddField(
            model_name='collaborationnet',
            name='network_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sci_impact.Network'),
            preserve_default=False,
        ),
    ]
