# Generated by Django 2.1.7 on 2019-05-14 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0024_auto_20190514_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='networkedge',
            name='attrs',
        ),
        migrations.AddField(
            model_name='networkedge',
            name='attrs',
            field=models.ManyToManyField(blank=True, null=True, to='sci_impact.CustomField'),
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='attrs',
        ),
        migrations.AddField(
            model_name='networknode',
            name='attrs',
            field=models.ManyToManyField(blank=True, null=True, to='sci_impact.CustomField'),
        ),
    ]
