# Generated by Django 2.1.7 on 2019-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0025_auto_20190514_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkedge',
            name='attrs',
            field=models.ManyToManyField(blank=True, to='sci_impact.CustomField'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='attrs',
            field=models.ManyToManyField(blank=True, to='sci_impact.CustomField'),
        ),
    ]
