# Generated by Django 2.1.7 on 2019-05-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0026_auto_20190514_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationnet',
            name='network_ptr',
        ),
        migrations.RemoveField(
            model_name='collaborationnet',
            name='scientist_A',
        ),
        migrations.RemoveField(
            model_name='collaborationnet',
            name='scientist_B',
        ),
        migrations.AddField(
            model_name='network',
            name='type',
            field=models.CharField(choices=[('directed', 'Directed'), ('undirected', 'Undirected')], default='undirected', max_length=50),
        ),
        migrations.AddField(
            model_name='networkedge',
            name='network',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Network'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CollaborationNet',
        ),
    ]
