# Generated by Django 2.1.7 on 2019-05-14 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0027_auto_20190514_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='most_recent_pi_inb_collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Scientist'),
        ),
    ]
