# Generated by Django 2.1.7 on 2019-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0028_scientist_most_recent_pi_inb_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='alternative_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
