# Generated by Django 2.1.7 on 2019-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0029_scientist_alternative_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientist',
            name='possible_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
