# Generated by Django 2.1.7 on 2019-05-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0030_scientist_possible_duplicate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='repo_ids',
            new_name='repo_id',
        ),
    ]
