# Generated by Django 2.1.7 on 2019-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0031_auto_20190527_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliation',
            name='article_citations',
            field=models.IntegerField(default=0),
        ),
    ]
