# Generated by Django 2.1.7 on 2019-05-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0032_affiliation_article_citations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliation',
            old_name='tools_citations',
            new_name='tool_citations',
        ),
        migrations.RenameField(
            model_name='scientist',
            old_name='articles_citations',
            new_name='article_citations',
        ),
        migrations.RenameField(
            model_name='scientist',
            old_name='tools_citations',
            new_name='tool_citations',
        ),
    ]
