# Generated by Django 2.1.7 on 2019-05-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0034_auto_20190527_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='affiliation',
            unique_together={('scientist', 'institution')},
        ),
    ]
