# Generated by Django 2.1.7 on 2019-06-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0036_article_inb_pi_as_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifactcitation',
            name='self_citation',
            field=models.BooleanField(default=False),
        ),
    ]
