# Generated by Django 2.1.7 on 2019-06-18 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0037_artifactcitation_self_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)])),
                ('avg_citations_field', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)])),
                ('end_year', models.IntegerField(default=2019)),
                ('total_publications', models.IntegerField(default=0)),
                ('total_weighted_impact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)])),
                ('publications', models.IntegerField()),
                ('citations', models.IntegerField()),
                ('avg_citations_per_publication', models.FloatField()),
                ('per_not_cited_publications', models.IntegerField()),
                ('per_self_citations', models.IntegerField()),
                ('impact_field', models.FloatField()),
                ('prop_publications_year', models.FloatField()),
                ('weighted_impact_field', models.FloatField()),
                ('impact_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Impact')),
            ],
        ),
    ]
