# Generated by Django 2.1.7 on 2019-06-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0042_auto_20190618_1704'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImpactDetails',
            new_name='ImpactDetail',
        ),
    ]
