# Generated by Django 2.1.7 on 2019-06-19 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0044_auto_20190618_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='impact',
            name='total_publications',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='impact',
            name='total_weighted_impact',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
