# Generated by Django 2.2.6 on 2019-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0047_auto_20190705_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='funding_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
