# Generated by Django 2.2.6 on 2019-10-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0048_article_funding_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
