# Generated by Django 2.2.6 on 2019-11-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0050_article_cited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_inb',
            field=models.BooleanField(default=False),
        ),
    ]
