# Generated by Django 2.2.6 on 2019-11-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('twitter_account', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('other', 'Other')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('funded_entity', models.TextField(blank=True, null=True)),
                ('overall_budget', models.IntegerField(blank=True, null=True)),
                ('budget_contribution_eu', models.IntegerField(blank=True, null=True)),
                ('coordinated_by', models.CharField(blank=True, max_length=300, null=True)),
                ('coordination_country', models.CharField(blank=True, max_length=300, null=True)),
                ('cordis_url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SIORMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdg', models.CharField(choices=[('poverty', 'No poverty'), ('hunger', 'Zero hunger'), ('health', 'Good health and well-being'), ('education', 'Quality education'), ('gender', 'Gender equality'), ('water', 'Clean water and sanitation'), ('energy', 'Affordable and clean energy'), ('work', 'Decent work and economic growth'), ('industry', 'Industry, innovation, and infrastructure'), ('inequalities', 'Reduced inequalities'), ('sustainable', 'Sustainable cities and communities'), ('consumption', 'Responsible consumption and production'), ('climate', 'Climate action'), ('life_water', 'Life below water'), ('life_land', 'Life on land'), ('peace', 'Peace, justice, and strong institutions'), ('partnership', 'Partnership for the goals')], max_length=300)),
                ('percentage_improvement', models.FloatField(blank=True, null=True)),
                ('description_improvement', models.TextField(blank=True, null=True)),
                ('sustainability', models.BooleanField(default=False)),
                ('replicability', models.BooleanField(default=False)),
                ('evidence', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.IntegerField(default=0, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_impact.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='project_reports/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_impact.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('sentence', models.TextField()),
                ('impact_mention', models.CharField(max_length=300)),
                ('mention_is_correct', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_impact.Publication')),
            ],
        ),
    ]
