# Generated by Django 2.2.6 on 2019-11-20 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactmention',
            old_name='report',
            new_name='publication',
        ),
        migrations.AlterField(
            model_name='siormeasurement',
            name='evidence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_impact.ImpactMention'),
            preserve_default=False,
        ),
    ]
