# Generated by Django 2.2.6 on 2019-11-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0002_auto_20191120_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='funded_entity',
            new_name='funded_by',
        ),
        migrations.AddField(
            model_name='project',
            name='twitter_hashtag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_contribution_eu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='overall_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
