# Generated by Django 2.2.6 on 2019-11-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0005_auto_20191121_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coordination_country',
        ),
    ]
