# Generated by Django 2.2.6 on 2019-11-21 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sci_impact', '0052_auto_20191106_1314'),
        ('social_impact', '0006_remove_project_coordination_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordination_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sci_impact.Country'),
        ),
    ]
