# Generated by Django 2.2.6 on 2019-11-21 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0007_project_coordination_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coordinator',
        ),
    ]
