# Generated by Django 2.2.6 on 2019-11-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0009_project_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='coordination_country',
            new_name='coordinator_country',
        ),
    ]
