# Generated by Django 2.2.6 on 2019-11-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0010_auto_20191121_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='docs/'),
        ),
    ]
