# Generated by Django 2.2.6 on 2019-11-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0011_auto_20191122_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='title',
            new_name='name',
        ),
    ]
