# Generated by Django 2.2.6 on 2019-11-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0013_socialimpactsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialimpactsearch',
            name='publications',
        ),
        migrations.AddField(
            model_name='socialimpactsearch',
            name='publications',
            field=models.ManyToManyField(to='social_impact.Publication'),
        ),
    ]
