# Generated by Django 2.2.6 on 2019-11-26 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0016_auto_20191125_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialimpactsearchpublication',
            options={'verbose_name_plural': 'Social Impact Publications'},
        ),
        migrations.AddField(
            model_name='impactmention',
            name='search',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='social_impact.SocialImpactSearch'),
            preserve_default=False,
        ),
    ]
