# Generated by Django 2.2.6 on 2019-11-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0017_auto_20191126_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='siormeasurement',
            name='scientific_evidence',
            field=models.BooleanField(default=False, verbose_name='Is the evidence a scientific publication oran official report?'),
        ),
        migrations.AlterField(
            model_name='siormeasurement',
            name='sdg',
            field=models.CharField(choices=[('poverty', 'SGD 1. No poverty'), ('hunger', 'SGD 2. Zero hunger'), ('health', 'SGD 3. Good health and well-being'), ('education', 'SGD 4. Quality education'), ('gender', 'SGD 5. Gender equality'), ('water', 'SGD 6. Clean water and sanitation'), ('energy', 'SGD 7. Affordable and clean energy'), ('work', 'SGD 8. Decent work and economic growth'), ('industry', 'SGD 9. Industry, innovation, and infrastructure'), ('inequalities', 'SGD 10. Reduced inequalities'), ('sustainable', 'SGD 11. Sustainable cities and communities'), ('consumption', 'SGD 12. Responsible consumption and production'), ('climate', 'SGD 13. Climate action'), ('life_water', 'SGD 14. Life below water'), ('life_land', 'SGD 15. Life on land'), ('peace', 'SGD 16. Peace, justice, and strong institutions'), ('partnership', 'SGD 17. Partnership for the goals'), ('other', 'Other societal objectives')], max_length=300, verbose_name='Social Target'),
        ),
    ]
