# Generated by Django 2.2.6 on 2019-11-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_impact', '0018_auto_20191126_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='siormeasurement',
            name='description_replicability',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siormeasurement',
            name='description_sustainability',
            field=models.TextField(blank=True, null=True),
        ),
    ]
