# Generated by Django 2.2.6 on 2019-11-26 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_impact', '0019_auto_20191126_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='siormeasurement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siormeasurement',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siormeasurement',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='siormeasurement',
            name='scientific_evidence',
            field=models.BooleanField(default=False, verbose_name='Is the evidence a scientific publication or an official report?'),
        ),
    ]
